// ============================================================
// prebuild.mjs — read deploy/ folder → generate deploy config
// ============================================================
// Scans ../../deploy/ for all * / *.json files and writes a
// generated JS module that contract.js imports at build time.
// Run: node scripts/prebuild.mjs

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { readdir, stat } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DEPLOY_DIR = join(__dirname, "..", "..", "..", "deploy");
const OUT_FILE   = join(__dirname, "..", "src", "utils", "deploy-generated.js");

async function walk(dir) {
  const entries = await readdir(dir);
  const files = [];
  for (const e of entries) {
    const p = join(dir, e);
    const s = await stat(p);
    if (s.isDirectory()) {
      files.push(...(await walk(p)));
    } else if (e.endsWith(".json")) {
      files.push(p);
    }
  }
  return files;
}

async function main() {
  /** @type {Record<string, Record<string, string>>}  chainId => contractName => address */
  const contracts = {};

  let files;
  try {
    files = await walk(DEPLOY_DIR);
  } catch {
    console.warn("[prebuild] deploy/ directory not found — writing empty config");
    writeGenerated(contracts);
    return;
  }

  for (const f of files) {
    try {
      const raw = readFileSync(f, "utf-8");
      const { name, address, chainId } = JSON.parse(raw);
      if (!name || !address || !chainId) continue;

      const chain = String(chainId);
      contracts[chain] ??= {};
      contracts[chain][name] = address;
    } catch (err) {
      console.warn(`[prebuild] skipping ${f}: ${err.message}`);
    }
  }

  writeGenerated(contracts);
  const names = new Set();
  for (const c of Object.values(contracts)) Object.keys(c).forEach((n) => names.add(n));
  console.log(`[prebuild] ✅ wrote config (chains: ${Object.keys(contracts).join(", ")}, contracts: ${[...names].join(", ")})`);
}

function writeGenerated(contracts) {
  const lines = [
    "// Auto-generated by scripts/prebuild.mjs — do not edit manually",
    `// Generated from ${DEPLOY_DIR}`,
    "export const CONTRACTS = " + JSON.stringify(contracts, null, 2) + ";",
    "",
  ];
  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, lines.join("\n"));
}

main().catch((err) => {
  console.error("[prebuild] failed:", err);
  process.exit(1);
});
